
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: oAigPHm8VZgjKtAmnNEFkF
    // Component: UfWUSFNaRL
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_olli_support.css"; // plasmic-import: oAigPHm8VZgjKtAmnNEFkF/projectcss
    import  "./PlasmicIndex.css" // plasmic-import: UfWUSFNaRL/css
  
    
    

    
    export type PlasmicIndex__VariantMembers = {
      unnamedVariant: "unnamedVariant";
    };
    export type PlasmicIndex__VariantsArgs = {
    unnamedVariant?: SingleBooleanChoiceArg<"unnamedVariant">
  };
    type VariantPropType = keyof PlasmicIndex__VariantsArgs;
    export const PlasmicIndex__VariantProps = new Array<VariantPropType>("unnamedVariant");
  

    
    export type PlasmicIndex__ArgsType = {};
    type ArgPropType = keyof PlasmicIndex__ArgsType;
    export const PlasmicIndex__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicIndex__OverridesType = {
    root?: p.Flex<"div">;
  };

    
    export interface DefaultIndexProps {
      unnamedVariant?: SingleBooleanChoiceArg<"unnamedVariant">
      className?: string;
    }
  

    
    function PlasmicIndex__RenderFunc(
      props: {
        variants: PlasmicIndex__VariantsArgs,
        args: PlasmicIndex__ArgsType
        overrides: PlasmicIndex__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        <React.Fragment>
    
    
    
      <div className={"plasmic_page_wrapper"}>
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_oAigPHm8VZgjKtAmnNEFkF", "Index__root___5Cnw9", { "Index__root__unnamedVariant___5Cnw9LdYr3": hasVariant(variants, "unnamedVariant", "unnamedVariant") })}
    
    />
  
      </div>
    
  </React.Fragment>
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicIndex__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicIndex__VariantsArgs;
        args?: PlasmicIndex__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicIndex__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicIndex__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicIndex__ArgProps,
          internalVariantPropNames: PlasmicIndex__VariantProps,
        });

        return PlasmicIndex__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicIndex";
      } else {
        func.displayName = `PlasmicIndex.${nodeName}`;
      }
      return func;
    }

    export const PlasmicIndex = Object.assign(
      // Top-level PlasmicIndex renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        

        // Metadata about props expected for PlasmicIndex
        internalVariantProps: PlasmicIndex__VariantProps,
        internalArgProps: PlasmicIndex__ArgProps,
      }
    );
  

    export default PlasmicIndex;
    /* prettier-ignore-end */
  