
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: oAigPHm8VZgjKtAmnNEFkF
    // Component: kCkGw3kPUN
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    import FaultCard from "..//FaultCard";  // plasmic-import: 4CgkUm2pVd/component
import DescriptiveFaultCard from "..//DescriptiveFaultCard";  // plasmic-import: pd3kCWpyEX/component
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_olli_support.css"; // plasmic-import: oAigPHm8VZgjKtAmnNEFkF/projectcss
    import  "./PlasmicTestBody.css" // plasmic-import: kCkGw3kPUN/css
  
    
    

    
    export type PlasmicTestBody__VariantMembers = {
      
    };
    export type PlasmicTestBody__VariantsArgs = {};
    type VariantPropType = keyof PlasmicTestBody__VariantsArgs;
    export const PlasmicTestBody__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicTestBody__ArgsType = {};
    type ArgPropType = keyof PlasmicTestBody__ArgsType;
    export const PlasmicTestBody__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicTestBody__OverridesType = {
    root?: p.Flex<"div">;
box?: p.Flex<"div">;
descriptiveFaultCard?: p.Flex<typeof DescriptiveFaultCard>;
  };

    
    export interface DefaultTestBodyProps {
      
      className?: string;
    }
  

    
    function PlasmicTestBody__RenderFunc(
      props: {
        variants: PlasmicTestBody__VariantsArgs,
        args: PlasmicTestBody__ArgsType
        overrides: PlasmicTestBody__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_oAigPHm8VZgjKtAmnNEFkF", "TestBody__root__g15Uw")}
    
    >
          
  <div
    
    data-plasmic-name={"box"}
    data-plasmic-override={overrides.box}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "TestBody__box__jQpc6")}
    
    >
          
  <FaultCard
    
    
    
    
    
    
    className={classNames("__wab_instance", "TestBody__faultCard__mNtfG")}
mediumPriority={("mediumPriority" as const)}
    
    />
  

  <FaultCard
    
    
    
    
    
    
    className={classNames("__wab_instance", "TestBody__faultCard__m6Qx4")}
noPriority={("noPriority" as const)}
    
    />
  

  <FaultCard
    
    
    
    
    
    
    className={classNames("__wab_instance", "TestBody__faultCard__qSd6")}
highPriority={("highPriority" as const)}
    
    />
  

  <FaultCard
    
    
    
    
    
    
    className={classNames("__wab_instance", "TestBody__faultCard___9M6Jb")}
lowPriority={("lowPriority" as const)}
    
    />
  

  <FaultCard
    
    
    
    
    
    
    className={classNames("__wab_instance", "TestBody__faultCard__iJwrj")}
    
    />
  

  <DescriptiveFaultCard
    
    data-plasmic-name={"descriptiveFaultCard"}
    data-plasmic-override={overrides.descriptiveFaultCard}
    
    
    
    className={classNames("__wab_instance", "TestBody__descriptiveFaultCard___8Ovmx")}
    
    />
  
        </div>
  
        </div>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "box", "descriptiveFaultCard"],
box: ["box", "descriptiveFaultCard"],
descriptiveFaultCard: ["descriptiveFaultCard"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div";
box: "div";
descriptiveFaultCard: typeof DescriptiveFaultCard
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicTestBody__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicTestBody__VariantsArgs;
        args?: PlasmicTestBody__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicTestBody__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicTestBody__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTestBody__ArgProps,
          internalVariantPropNames: PlasmicTestBody__VariantProps,
        });

        return PlasmicTestBody__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicTestBody";
      } else {
        func.displayName = `PlasmicTestBody.${nodeName}`;
      }
      return func;
    }

    export const PlasmicTestBody = Object.assign(
      // Top-level PlasmicTestBody renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        box: makeNodeComponent("box"),
descriptiveFaultCard: makeNodeComponent("descriptiveFaultCard"),

        // Metadata about props expected for PlasmicTestBody
        internalVariantProps: PlasmicTestBody__VariantProps,
        internalArgProps: PlasmicTestBody__ArgProps,
      }
    );
  

    export default PlasmicTestBody;
    /* prettier-ignore-end */
  