
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: oAigPHm8VZgjKtAmnNEFkF
    // Component: KcSIlmSgOq
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_olli_support.css"; // plasmic-import: oAigPHm8VZgjKtAmnNEFkF/projectcss
    import  "./PlasmicFaultNameNumber.css" // plasmic-import: KcSIlmSgOq/css
  
    
    

    
    export type PlasmicFaultNameNumber__VariantMembers = {
      highPriority: "highPriority";
mediumPriority: "mediumPriority";
lowPriority: "lowPriority";
noPriority: "noPriority";
    };
    export type PlasmicFaultNameNumber__VariantsArgs = {
    highPriority?: SingleBooleanChoiceArg<"highPriority">
mediumPriority?: SingleBooleanChoiceArg<"mediumPriority">
lowPriority?: SingleBooleanChoiceArg<"lowPriority">
noPriority?: SingleBooleanChoiceArg<"noPriority">
  };
    type VariantPropType = keyof PlasmicFaultNameNumber__VariantsArgs;
    export const PlasmicFaultNameNumber__VariantProps = new Array<VariantPropType>("highPriority","mediumPriority","lowPriority","noPriority");
  

    
    export type PlasmicFaultNameNumber__ArgsType = {
    children?: React.ReactNode
  };
    type ArgPropType = keyof PlasmicFaultNameNumber__ArgsType;
    export const PlasmicFaultNameNumber__ArgProps = new Array<ArgPropType>("children");
  

    export type PlasmicFaultNameNumber__OverridesType = {
    root?: p.Flex<"div">;
  };

    
    export interface DefaultFaultNameNumberProps {
      children?: React.ReactNode;
highPriority?: SingleBooleanChoiceArg<"highPriority">;
mediumPriority?: SingleBooleanChoiceArg<"mediumPriority">;
lowPriority?: SingleBooleanChoiceArg<"lowPriority">;
noPriority?: SingleBooleanChoiceArg<"noPriority">
      className?: string;
    }
  

    
    function PlasmicFaultNameNumber__RenderFunc(
      props: {
        variants: PlasmicFaultNameNumber__VariantsArgs,
        args: PlasmicFaultNameNumber__ArgsType
        overrides: PlasmicFaultNameNumber__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_oAigPHm8VZgjKtAmnNEFkF", "FaultNameNumber__root__ojtDb", { "FaultNameNumber__root__highPriority__ojtDb2MJaa": hasVariant(variants, "highPriority", "highPriority"), "FaultNameNumber__root__lowPriority__ojtDbY7Mo7": hasVariant(variants, "lowPriority", "lowPriority"), "FaultNameNumber__root__mediumPriority__ojtDbNtJaa": hasVariant(variants, "mediumPriority", "mediumPriority"), "FaultNameNumber__root__noPriority__ojtDb4BMu4": hasVariant(variants, "noPriority", "noPriority") })}
    
    >
          <p.PlasmicSlot
      defaultContents={"Fault Name - Number"}
      value={args.children}
      className={classNames("FaultNameNumber__slotChildren___7VYmG", { "FaultNameNumber__slotChildren__highPriority___7VYmG2MJaa": hasVariant(variants, "highPriority", "highPriority"), "FaultNameNumber__slotChildren__lowPriority___7VYmGy7Mo7": hasVariant(variants, "lowPriority", "lowPriority"), "FaultNameNumber__slotChildren__mediumPriority___7VYmGntJaa": hasVariant(variants, "mediumPriority", "mediumPriority"), "FaultNameNumber__slotChildren__noPriority___7VYmG4BMu4": hasVariant(variants, "noPriority", "noPriority") })} />
        </div>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicFaultNameNumber__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicFaultNameNumber__VariantsArgs;
        args?: PlasmicFaultNameNumber__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicFaultNameNumber__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicFaultNameNumber__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFaultNameNumber__ArgProps,
          internalVariantPropNames: PlasmicFaultNameNumber__VariantProps,
        });

        return PlasmicFaultNameNumber__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicFaultNameNumber";
      } else {
        func.displayName = `PlasmicFaultNameNumber.${nodeName}`;
      }
      return func;
    }

    export const PlasmicFaultNameNumber = Object.assign(
      // Top-level PlasmicFaultNameNumber renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        

        // Metadata about props expected for PlasmicFaultNameNumber
        internalVariantProps: PlasmicFaultNameNumber__VariantProps,
        internalArgProps: PlasmicFaultNameNumber__ArgProps,
      }
    );
  

    export default PlasmicFaultNameNumber;
    /* prettier-ignore-end */
  