
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: oAigPHm8VZgjKtAmnNEFkF
    // Component: fNhXGijyuG
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_olli_support.css"; // plasmic-import: oAigPHm8VZgjKtAmnNEFkF/projectcss
    import  "./PlasmicSection.css" // plasmic-import: fNhXGijyuG/css
  
    
    

    
    export type PlasmicSection__VariantMembers = {
      
    };
    export type PlasmicSection__VariantsArgs = {};
    type VariantPropType = keyof PlasmicSection__VariantsArgs;
    export const PlasmicSection__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicSection__ArgsType = {};
    type ArgPropType = keyof PlasmicSection__ArgsType;
    export const PlasmicSection__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicSection__OverridesType = {
    root?: p.Flex<"div">;
  };

    
    export interface DefaultSectionProps {
      
      className?: string;
    }
  

    
    function PlasmicSection__RenderFunc(
      props: {
        variants: PlasmicSection__VariantsArgs,
        args: PlasmicSection__ArgsType
        overrides: PlasmicSection__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_oAigPHm8VZgjKtAmnNEFkF", "Section__root__vBwq")}
    
    />
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicSection__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicSection__VariantsArgs;
        args?: PlasmicSection__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicSection__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicSection__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSection__ArgProps,
          internalVariantPropNames: PlasmicSection__VariantProps,
        });

        return PlasmicSection__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicSection";
      } else {
        func.displayName = `PlasmicSection.${nodeName}`;
      }
      return func;
    }

    export const PlasmicSection = Object.assign(
      // Top-level PlasmicSection renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        

        // Metadata about props expected for PlasmicSection
        internalVariantProps: PlasmicSection__VariantProps,
        internalArgProps: PlasmicSection__ArgProps,
      }
    );
  

    export default PlasmicSection;
    /* prettier-ignore-end */
  