
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: oAigPHm8VZgjKtAmnNEFkF
    // Component: aahZZJy75V
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_olli_support.css"; // plasmic-import: oAigPHm8VZgjKtAmnNEFkF/projectcss
    import  "./PlasmicNeedSupportButton.css" // plasmic-import: aahZZJy75V/css
  
    
    

    
    export type PlasmicNeedSupportButton__VariantMembers = {
      
    };
    export type PlasmicNeedSupportButton__VariantsArgs = {};
    type VariantPropType = keyof PlasmicNeedSupportButton__VariantsArgs;
    export const PlasmicNeedSupportButton__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicNeedSupportButton__ArgsType = {};
    type ArgPropType = keyof PlasmicNeedSupportButton__ArgsType;
    export const PlasmicNeedSupportButton__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicNeedSupportButton__OverridesType = {
    root?: p.Flex<"div">;
box?: p.Flex<"div">;
  };

    
    export interface DefaultNeedSupportButtonProps {
      
      className?: string;
    }
  

    
    function PlasmicNeedSupportButton__RenderFunc(
      props: {
        variants: PlasmicNeedSupportButton__VariantsArgs,
        args: PlasmicNeedSupportButton__ArgsType
        overrides: PlasmicNeedSupportButton__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_oAigPHm8VZgjKtAmnNEFkF", "NeedSupportButton__root__kjpuF")}
    
    >
          
  <div
    
    data-plasmic-name={"box"}
    data-plasmic-override={overrides.box}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "NeedSupportButton__box___5My4S")}
    
    >
          { "Need Support" }
        </div>
  
        </div>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "box"],
box: ["box"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div";
box: "div"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicNeedSupportButton__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicNeedSupportButton__VariantsArgs;
        args?: PlasmicNeedSupportButton__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicNeedSupportButton__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicNeedSupportButton__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicNeedSupportButton__ArgProps,
          internalVariantPropNames: PlasmicNeedSupportButton__VariantProps,
        });

        return PlasmicNeedSupportButton__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicNeedSupportButton";
      } else {
        func.displayName = `PlasmicNeedSupportButton.${nodeName}`;
      }
      return func;
    }

    export const PlasmicNeedSupportButton = Object.assign(
      // Top-level PlasmicNeedSupportButton renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        box: makeNodeComponent("box"),

        // Metadata about props expected for PlasmicNeedSupportButton
        internalVariantProps: PlasmicNeedSupportButton__VariantProps,
        internalArgProps: PlasmicNeedSupportButton__ArgProps,
      }
    );
  

    export default PlasmicNeedSupportButton;
    /* prettier-ignore-end */
  