
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: oAigPHm8VZgjKtAmnNEFkF
    // Component: aKm6LjL0cX
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_olli_support.css"; // plasmic-import: oAigPHm8VZgjKtAmnNEFkF/projectcss
    import  "./PlasmicFixedButton.css" // plasmic-import: aKm6LjL0cX/css
  
    
    

    
    export type PlasmicFixedButton__VariantMembers = {
      
    };
    export type PlasmicFixedButton__VariantsArgs = {};
    type VariantPropType = keyof PlasmicFixedButton__VariantsArgs;
    export const PlasmicFixedButton__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicFixedButton__ArgsType = {};
    type ArgPropType = keyof PlasmicFixedButton__ArgsType;
    export const PlasmicFixedButton__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicFixedButton__OverridesType = {
    root?: p.Flex<"div">;
box?: p.Flex<"div">;
  };

    
    export interface DefaultFixedButtonProps {
      
      className?: string;
    }
  

    
    function PlasmicFixedButton__RenderFunc(
      props: {
        variants: PlasmicFixedButton__VariantsArgs,
        args: PlasmicFixedButton__ArgsType
        overrides: PlasmicFixedButton__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_oAigPHm8VZgjKtAmnNEFkF", "FixedButton__root__ajeK")}
    
    >
          
  <div
    
    data-plasmic-name={"box"}
    data-plasmic-override={overrides.box}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "FixedButton__box__evfEg")}
    
    >
          { "Fixed issue" }
        </div>
  
        </div>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "box"],
box: ["box"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div";
box: "div"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicFixedButton__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicFixedButton__VariantsArgs;
        args?: PlasmicFixedButton__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicFixedButton__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicFixedButton__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFixedButton__ArgProps,
          internalVariantPropNames: PlasmicFixedButton__VariantProps,
        });

        return PlasmicFixedButton__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicFixedButton";
      } else {
        func.displayName = `PlasmicFixedButton.${nodeName}`;
      }
      return func;
    }

    export const PlasmicFixedButton = Object.assign(
      // Top-level PlasmicFixedButton renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        box: makeNodeComponent("box"),

        // Metadata about props expected for PlasmicFixedButton
        internalVariantProps: PlasmicFixedButton__VariantProps,
        internalArgProps: PlasmicFixedButton__ArgProps,
      }
    );
  

    export default PlasmicFixedButton;
    /* prettier-ignore-end */
  