
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: oAigPHm8VZgjKtAmnNEFkF
    // Component: _WrKthJl9L
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_olli_support.css"; // plasmic-import: oAigPHm8VZgjKtAmnNEFkF/projectcss
    import  "./PlasmicBaseCard.css" // plasmic-import: _WrKthJl9L/css
  
    
    

    
    export type PlasmicBaseCard__VariantMembers = {
      
    };
    export type PlasmicBaseCard__VariantsArgs = {};
    type VariantPropType = keyof PlasmicBaseCard__VariantsArgs;
    export const PlasmicBaseCard__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicBaseCard__ArgsType = {
    baseCardText?: string
  };
    type ArgPropType = keyof PlasmicBaseCard__ArgsType;
    export const PlasmicBaseCard__ArgProps = new Array<ArgPropType>("baseCardText");
  

    export type PlasmicBaseCard__OverridesType = {
    root?: p.Flex<"div">;
box?: p.Flex<"div">;
  };

    
    export interface DefaultBaseCardProps {
      baseCardText?: string
      className?: string;
    }
  

    
    function PlasmicBaseCard__RenderFunc(
      props: {
        variants: PlasmicBaseCard__VariantsArgs,
        args: PlasmicBaseCard__ArgsType
        overrides: PlasmicBaseCard__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <p.Stack
    as={"div"}
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_oAigPHm8VZgjKtAmnNEFkF", "BaseCard__root__lDtry")}
    
    >
          
  <div
    
    data-plasmic-name={"box"}
    data-plasmic-override={overrides.box}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "BaseCard__box__gkzS2")}
    
    >
          { "" }
        </div>
  
        </p.Stack>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "box"],
box: ["box"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div";
box: "div"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicBaseCard__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicBaseCard__VariantsArgs;
        args?: PlasmicBaseCard__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicBaseCard__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicBaseCard__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBaseCard__ArgProps,
          internalVariantPropNames: PlasmicBaseCard__VariantProps,
        });

        return PlasmicBaseCard__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicBaseCard";
      } else {
        func.displayName = `PlasmicBaseCard.${nodeName}`;
      }
      return func;
    }

    export const PlasmicBaseCard = Object.assign(
      // Top-level PlasmicBaseCard renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        box: makeNodeComponent("box"),

        // Metadata about props expected for PlasmicBaseCard
        internalVariantProps: PlasmicBaseCard__VariantProps,
        internalArgProps: PlasmicBaseCard__ArgProps,
      }
    );
  

    export default PlasmicBaseCard;
    /* prettier-ignore-end */
  