
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: oAigPHm8VZgjKtAmnNEFkF
    // Component: R4ziHmPkBc
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_olli_support.css"; // plasmic-import: oAigPHm8VZgjKtAmnNEFkF/projectcss
    import  "./PlasmicFooter.css" // plasmic-import: R4ziHmPkBc/css
  
    import DownloadsvgIcon from "./PlasmicIcon__Downloadsvg";  // plasmic-import: XQCEmem7d/icon
import IconIcon from "./PlasmicIcon__Icon";  // plasmic-import: j_qN5ag7w7/icon
import Icon2Icon from "./PlasmicIcon__Icon2";  // plasmic-import: FO4lAnPQ-P/icon
import Icon3Icon from "./PlasmicIcon__Icon3";  // plasmic-import: YrWQcoJNlc/icon
    

    
    export type PlasmicFooter__VariantMembers = {
      
    };
    export type PlasmicFooter__VariantsArgs = {};
    type VariantPropType = keyof PlasmicFooter__VariantsArgs;
    export const PlasmicFooter__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicFooter__ArgsType = {};
    type ArgPropType = keyof PlasmicFooter__ArgsType;
    export const PlasmicFooter__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicFooter__OverridesType = {
    root?: p.Flex<"div">;
box?: p.Flex<"div">;
  };

    
    export interface DefaultFooterProps {
      
      className?: string;
    }
  

    
    function PlasmicFooter__RenderFunc(
      props: {
        variants: PlasmicFooter__VariantsArgs,
        args: PlasmicFooter__ArgsType
        overrides: PlasmicFooter__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_oAigPHm8VZgjKtAmnNEFkF", "Footer__root__lIcsN")}
    
    >
          
  <div
    
    data-plasmic-name={"box"}
    data-plasmic-override={overrides.box}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Footer__box__quret")}
    
    >
          
  <DownloadsvgIcon
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__svg", "Footer__svg__oHmK9")}
role={"img"}
    
    />
  

  <IconIcon
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__svg", "Footer__svg__btlpp")}
role={"img"}
    
    />
  

  <Icon2Icon
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__svg", "Footer__svg__jzZry")}
role={"img"}
    
    />
  

  <Icon3Icon
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__svg", "Footer__svg__tbbWn")}
role={"img"}
    
    />
  
        </div>
  
        </div>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "box"],
box: ["box"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div";
box: "div"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicFooter__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicFooter__VariantsArgs;
        args?: PlasmicFooter__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicFooter__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicFooter__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFooter__ArgProps,
          internalVariantPropNames: PlasmicFooter__VariantProps,
        });

        return PlasmicFooter__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicFooter";
      } else {
        func.displayName = `PlasmicFooter.${nodeName}`;
      }
      return func;
    }

    export const PlasmicFooter = Object.assign(
      // Top-level PlasmicFooter renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        box: makeNodeComponent("box"),

        // Metadata about props expected for PlasmicFooter
        internalVariantProps: PlasmicFooter__VariantProps,
        internalArgProps: PlasmicFooter__ArgProps,
      }
    );
  

    export default PlasmicFooter;
    /* prettier-ignore-end */
  